kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "integration-manager-worker.fullname" . }}
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
  labels:
    app: integration-manager-worker
    chart: {{ template "integration-manager-worker.chart" . }}
    release: {{ .Release.Name | quote }}
    destinationId: {{ quote .Values.destinationId }}
